dataloader_details:
  K: 20
  apply_mask_percentage: 1.0
  clips_directory: Dataset/polarbears_h5files/clips/
  cooccurrences_filepath: Dataset/polarbears_h5files/Cooccurrences.json
  is_override: true
  mask_path: ''
  mode: positive_negative
  num_frames: 5
  override_value: 5000
  total_frames: 20
  transformations:
  - random_resized_crop
  - horizontal_flip
  - gaussian_blur
  - color_jitter
  zfill_num: 4
model_details:
  dino_model_name: facebook/dinov2-small
  dropout_rate: 0.1
  embedding_dim: 384
  flatten_channels: false
  freeze_image_model: true
  is_append_avg_emb: true
  latent_dim: 384
  model_type: recurrent_perceiver
  num_heads: 8
  num_latents: 257
  num_tf_layers: 2
  output_dim: 384
  raw_input_dim: null
  use_embeddings: true
  use_raw_input: false
training_details:
  accumulation_steps: 1
  anchor_dino_model: null
  anchor_function_details:
    similarity_measure: euclidean_distance
    type: hard
  batch_size: 30
  clip_value: null
  criterion_details:
    margin: 1.0
    name: triplet_margin_loss
    p: 2
  epochs: 10
  log_directory: results/full_model_training/rovfv1_st_no_mask_aug_0p5_fps_polarbear/
  optimizer_details:
    lr: 0.0001
    name: adamw
    weight_decay: 0.01
  scheduler_details:
    decay_steps: 4750
    end_lr: 0.0001
    max_lr: 0.005
    name: warmup_cosine_decay_scheduler
    start_lr: 0.001
    warmup_steps: 250
